# This file has been generated by a machine. Do NOT modify it directly.
# To modify, go to the "numpy_teacher/rewrite_rules/_codegen/__main__.py" file and
# modify the code that generated this code.

from ast import *
from ._core import *
from ._comprehensions import *


class NumpyRewriter(Rewriter):
    def visit_ListComp(self, node):
        match node:
            # forall([var('v0'), 'in0'], '[v0 for v0 in in0]', 'list(in0)')
            case ListComp(
                elt=Name(id=v0, ctx=Load()),
                generators=[
                    comprehension(
                        target=Name(id=_v0_0, ctx=Store()),
                        iter=in0,
                        ifs=[],
                        is_async=0)]) if v0 == _v0_0:
                nnode = Call(
                    func=Name(id='list', ctx=Load()),
                    args=[
                        in0],
                    keywords=[])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall([var('v0'), 'in0', 'in1'], '[v0 for v0 in in0 if in1]', 'list(filter(lambda v0: in1, in0))')
            case ListComp(
                elt=Name(id=v0, ctx=Load()),
                generators=[
                    comprehension(
                        target=Name(id=_v0_0, ctx=Store()),
                        iter=in0,
                        ifs=[
                            in1],
                        is_async=0)]) if v0 == _v0_0:
                nnode = Call(
                    func=Name(id='list', ctx=Load()),
                    args=[
                        Call(
                            func=Name(id='filter', ctx=Load()),
                            args=[
                                Lambda(
                                    args=arguments(
                                        posonlyargs=[],
                                        args=[
                                            arg(arg=v0)],
                                        kwonlyargs=[],
                                        kw_defaults=[],
                                        defaults=[]),
                                    body=in1),
                                in0],
                            keywords=[])],
                    keywords=[])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # This collapses multiple 'if's that follow each other in the same comprehension
            # into one 'if' with multiple 'and's
            # TODO: Generalize
            case ListComp(
                elt=Name(id=v0, ctx=Load()),
                generators=[
                    comprehension(
                        target=Name(id=_v0_0, ctx=Store()),
                        iter=in0,
                        ifs=in1,
                        is_async=0)]) if v0 == _v0_0 and len(in1) > 0:
                nnode = Call(
                    func=Name(id='list', ctx=Load()),
                    args=[
                        Call(
                            func=Name(id='filter', ctx=Load()),
                            args=[
                                Lambda(
                                    args=arguments(
                                        posonlyargs=[],
                                        args=[
                                            arg(arg=v0)],
                                        kwonlyargs=[],
                                        kw_defaults=[],
                                        defaults=[]),
                                    body=BoolOp(
                                        op=And(),
                                        values=in1
                                    )),
                                in0],
                            keywords=[])],
                    keywords=[])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            case _:
                return self.generic_visit(node)

    def visit_Call(self, node):
        match node:
            # forall([(ListComp() | List() | BinOp(op=Add() | Mult())) as in0, 'out'], 'np.array(in0)', 'out', 'eval', ('body', -1, 'value'), '(out := analyze_list_to_array(in0, self))')
            case Call(
                func=Attribute(
                    value=Name(id=self.aliases.numpy, ctx=Load()),
                    attr='array',
                    ctx=Load()),
                args=[
                    (ListComp() | List() | BinOp(op=Add() | Mult())) as in0],
                keywords=[]) if (out := analyze_list_to_array(in0, self)):
                nnode = out
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall(['*args'], 'np.array(range(*args))', 'np.arange(*args)')
            case Call(
                func=Attribute(
                    value=Name(id=self.aliases.numpy, ctx=Load()),
                    attr='array',
                    ctx=Load()),
                args=[
                    Call(
                        func=Name(id='range', ctx=Load()),
                        args=[
                            *args],
                        keywords=[])],
                keywords=[]):
                nnode = Call(
                    func=Attribute(
                        value=Name(id=self.aliases.numpy, ctx=Load()),
                        attr='arange',
                        ctx=Load()),
                    args=[
                        *args],
                    keywords=[])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall(['in0'], 'np.array(list(in0))', 'np.array(in0)')
            case Call(
                func=Attribute(
                    value=Name(id=self.aliases.numpy, ctx=Load()),
                    attr='array',
                    ctx=Load()),
                args=[
                    Call(
                        func=Name(id='list', ctx=Load()),
                        args=[
                            in0],
                        keywords=[])],
                keywords=[]):
                nnode = Call(
                    func=Attribute(
                        value=Name(id=self.aliases.numpy, ctx=Load()),
                        attr='array',
                        ctx=Load()),
                    args=[
                        in0],
                    keywords=[])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall(['in0', 'in1'], 'np.array(filter(in0, in1))', 'np.extract(in0, np.array(in1))')
            case Call(
                func=Attribute(
                    value=Name(id=self.aliases.numpy, ctx=Load()),
                    attr='array',
                    ctx=Load()),
                args=[
                    Call(
                        func=Name(id='filter', ctx=Load()),
                        args=[
                            in0,
                            in1],
                        keywords=[])],
                keywords=[]):
                nnode = Call(
                    func=Attribute(
                        value=Name(id=self.aliases.numpy, ctx=Load()),
                        attr='extract',
                        ctx=Load()),
                    args=[
                        in0,
                        Call(
                            func=Attribute(
                                value=Name(id=self.aliases.numpy, ctx=Load()),
                                attr='array',
                                ctx=Load()),
                            args=[
                                in1],
                            keywords=[])],
                    keywords=[])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall([var('v0'), 'in0', 'in1'], 'np.array([in1 for v0 in in0])', 'np.full(sum(1 for v0 in in0), in1)', 'eval', ('body', -1, 'value'), 'is_pure(in1)')
            case Call(
                func=Attribute(
                    value=Name(id=self.aliases.numpy, ctx=Load()),
                    attr='array',
                    ctx=Load()),
                args=[
                    ListComp(
                        elt=in1,
                        generators=[
                            comprehension(
                                target=Name(id=v0, ctx=Store()),
                                iter=in0,
                                ifs=[],
                                is_async=0)])],
                keywords=[]) if is_pure(in1):
                nnode = Call(
                    func=Attribute(
                        value=Name(id=self.aliases.numpy, ctx=Load()),
                        attr='full',
                        ctx=Load()),
                    args=[
                        Call(
                            func=Name(id='sum', ctx=Load()),
                            args=[
                                GeneratorExp(
                                    elt=Constant(value=1),
                                    generators=[
                                        comprehension(
                                            target=Name(id=v0, ctx=Store()),
                                            iter=in0,
                                            ifs=[],
                                            is_async=0)])],
                            keywords=[]),
                        in1],
                    keywords=[])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall(['in0', var('v0'), (Call(func=f0)) as in0], 'sum(1 for v0 in x0)', 'len(in0)', 'eval', ('body', -1, 'value'), 'is_sized(f0)')
            case Call(
                func=Name(id='sum', ctx=Load()),
                args=[
                    GeneratorExp(
                        elt=Constant(value=1),
                        generators=[
                            comprehension(
                                target=Name(id=v0, ctx=Store()),
                                iter=(Call(func=f0)) as in0,
                                ifs=[],
                                is_async=0)])],
                keywords=[]) if is_sized(f0):
                nnode = Call(
                    func=Name(id='len', ctx=Load()),
                    args=[
                        in0],
                    keywords=[])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall(['in0'], 'len(range(in0))', 'max(in0, 0)')
            case Call(
                func=Name(id='len', ctx=Load()),
                args=[
                    Call(
                        func=Name(id='range', ctx=Load()),
                        args=[
                            in0],
                        keywords=[])],
                keywords=[]):
                nnode = Call(
                    func=Name(id='max', ctx=Load()),
                    args=[
                        in0,
                        Constant(value=0)],
                    keywords=[])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall(['in0', 'in1'], 'len(range(in0, in1))', 'max(-in0 + in1, 0)')
            case Call(
                func=Name(id='len', ctx=Load()),
                args=[
                    Call(
                        func=Name(id='range', ctx=Load()),
                        args=[
                            in0,
                            in1],
                        keywords=[])],
                keywords=[]):
                nnode = Call(
                    func=Name(id='max', ctx=Load()),
                    args=[
                        BinOp(
                            left=UnaryOp(op=USub(), operand=in0),
                            op=Add(),
                            right=in1),
                        Constant(value=0)],
                    keywords=[])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall([Constant(value=c0), Constant(value=c1), Constant(value=min(c0, c1))], 'min(c0, c1)', '_const')
            case Call(
                func=Name(id='min', ctx=Load()),
                args=[
                    Constant(value=c0),
                    Constant(value=c1)],
                keywords=[]):
                nnode = Constant(value=min(c0, c1))
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall([Constant(value=c0), Constant(value=c1), Constant(value=max(c0, c1))], 'max(c0, c1)', '_const')
            case Call(
                func=Name(id='max', ctx=Load()),
                args=[
                    Constant(value=c0),
                    Constant(value=c1)],
                keywords=[]):
                nnode = Constant(value=max(c0, c1))
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall(['*cargs'], 'min(*cargs)', 'cval', 'eval', ('body', -1, 'value'), '(cval := are_all_constants(cargs))')
            case Call(
                func=Name(id='min', ctx=Load()),
                args=[
                    *cargs],
                keywords=[]) if (cval := are_all_constants(cargs)):
                nnode = Name(id='cval', ctx=Load())
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall(['*cargs'], 'max(*cargs)', 'cval', 'eval', ('body', -1, 'value'), '(cval := are_all_constants(cargs))')
            case Call(
                func=Name(id='max', ctx=Load()),
                args=[
                    *cargs],
                keywords=[]) if (cval := are_all_constants(cargs)):
                nnode = Name(id='cval', ctx=Load())
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall([(Constant() as inner), (Constant(0) | Constant(-1)), 'inner'], 'np.expand_dims(inner_match, zono)', 'np.full(1, inner)')
            case Call(
                func=Attribute(
                    value=Name(id=self.aliases.numpy, ctx=Load()),
                    attr='expand_dims',
                    ctx=Load()),
                args=[
                    (Constant() as inner),
                    (Constant(0) | Constant(-1))],
                keywords=[]):
                nnode = Call(
                    func=Attribute(
                        value=Name(id=self.aliases.numpy, ctx=Load()),
                        attr='full',
                        ctx=Load()),
                    args=[
                        Constant(value=1),
                        inner],
                    keywords=[])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall(['inner', 'dims', 'rdim', dims_extend(dims, Constant(1), rdim)], 'np.expand_dims(np.full(dims, inner), rdim)', 'np.full(new_dims, inner)')
            case Call(
                func=Attribute(
                    value=Name(id=self.aliases.numpy, ctx=Load()),
                    attr='expand_dims',
                    ctx=Load()),
                args=[
                    Call(
                        func=Attribute(
                            value=Name(id=self.aliases.numpy, ctx=Load()),
                            attr='full',
                            ctx=Load()),
                        args=[
                            dims,
                            inner],
                        keywords=[]),
                    rdim],
                keywords=[]):
                nnode = Call(
                    func=Attribute(
                        value=Name(id=self.aliases.numpy, ctx=Load()),
                        attr='full',
                        ctx=Load()),
                    args=[
                        dims_extend(dims, Constant(1), rdim),
                        inner],
                    keywords=[])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall(['inner', 'reps', 'dims', 'rdim', dim_repeat(dims, reps, rdim)], 'np.repeat(np.full(dims, inner), reps, rdim)', 'np.full(new_dims, inner)')
            case Call(
                func=Attribute(
                    value=Name(id=self.aliases.numpy, ctx=Load()),
                    attr='repeat',
                    ctx=Load()),
                args=[
                    Call(
                        func=Attribute(
                            value=Name(id=self.aliases.numpy, ctx=Load()),
                            attr='full',
                            ctx=Load()),
                        args=[
                            dims,
                            inner],
                        keywords=[]),
                    reps,
                    rdim],
                keywords=[]):
                nnode = Call(
                    func=Attribute(
                        value=Name(id=self.aliases.numpy, ctx=Load()),
                        attr='full',
                        ctx=Load()),
                    args=[
                        dim_repeat(dims, reps, rdim),
                        inner],
                    keywords=[])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall(['inner', 'dim'], 'np.stack([inner], dim)', 'np.expand_dims(inner, dim)')
            case Call(
                func=Attribute(
                    value=Name(id=self.aliases.numpy, ctx=Load()),
                    attr='stack',
                    ctx=Load()),
                args=[
                    List(
                        elts=[
                            inner],
                        ctx=Load()),
                    dim],
                keywords=[]):
                nnode = Call(
                    func=Attribute(
                        value=Name(id=self.aliases.numpy, ctx=Load()),
                        attr='expand_dims',
                        ctx=Load()),
                    args=[
                        inner,
                        dim],
                    keywords=[])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall(['inner', 'dim'], 'np.stack(1 * [inner], dim)', 'np.expand_dims(inner, dim)')
            case Call(
                func=Attribute(
                    value=Name(id=self.aliases.numpy, ctx=Load()),
                    attr='stack',
                    ctx=Load()),
                args=[
                    BinOp(
                        left=Constant(value=1),
                        op=Mult(),
                        right=List(
                            elts=[
                                inner],
                            ctx=Load())),
                    dim],
                keywords=[]):
                nnode = Call(
                    func=Attribute(
                        value=Name(id=self.aliases.numpy, ctx=Load()),
                        attr='expand_dims',
                        ctx=Load()),
                    args=[
                        inner,
                        dim],
                    keywords=[])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall(['inner', 'dim'], 'np.stack([inner] * 1, dim)', 'np.expand_dims(inner, dim)')
            case Call(
                func=Attribute(
                    value=Name(id=self.aliases.numpy, ctx=Load()),
                    attr='stack',
                    ctx=Load()),
                args=[
                    BinOp(
                        left=List(
                            elts=[
                                inner],
                            ctx=Load()),
                        op=Mult(),
                        right=Constant(value=1)),
                    dim],
                keywords=[]):
                nnode = Call(
                    func=Attribute(
                        value=Name(id=self.aliases.numpy, ctx=Load()),
                        attr='expand_dims',
                        ctx=Load()),
                    args=[
                        inner,
                        dim],
                    keywords=[])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            case _:
                return self.generic_visit(node)

    def visit_UnaryOp(self, node):
        match node:
            # forall([Constant(value=c0), Constant(value=+c0)], '+c0', '_const')
            case UnaryOp(op=UAdd(), operand=Constant(value=c0)):
                nnode = Constant(value=+c0)
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall([Constant(value=c0), Constant(value=-c0)], '-c0', '_const')
            case UnaryOp(op=USub(), operand=Constant(value=c0)):
                nnode = Constant(value=-c0)
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall([Constant(value=c0), Constant(value=not c0)], 'not c0', '_const')
            case UnaryOp(op=Not(), operand=Constant(value=c0)):
                nnode = Constant(value=not c0)
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            case _:
                return self.generic_visit(node)

    def visit_BinOp(self, node):
        match node:
            # forall([Constant(value=c0), Constant(value=c1), Constant(value=c0 + c1)], 'c0 + c1', '_const')
            case BinOp(left=Constant(value=c0), op=Add(), right=Constant(value=c1)):
                nnode = Constant(value=c0 + c1)
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall([Constant(value=c0), Constant(value=c1), Constant(value=c0 - c1)], 'c0 - c1', '_const')
            case BinOp(left=Constant(value=c0), op=Sub(), right=Constant(value=c1)):
                nnode = Constant(value=c0 - c1)
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall([Constant(value=c0), Constant(value=c1), Constant(value=c0 * c1)], 'c0 * c1', '_const')
            case BinOp(left=Constant(value=c0), op=Mult(), right=Constant(value=c1)):
                nnode = Constant(value=c0 * c1)
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall([Constant(value=c0), Constant(value=c1), Constant(value=c0 / c1)], 'c0 / c1', '_const')
            case BinOp(left=Constant(value=c0), op=Div(), right=Constant(value=c1)):
                nnode = Constant(value=c0 / c1)
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall([Constant(value=c0), Constant(value=c1), Constant(value=c0 ** c1)], 'c0 ** c1', '_const')
            case BinOp(left=Constant(value=c0), op=Pow(), right=Constant(value=c1)):
                nnode = Constant(value=c0 ** c1)
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall(['in0', 'in1'], '-in0 + in1', 'in1 - in0', 'eval', ('body', -1, 'value'), 'is_pure(in0) or is_pure(in1)')
            case BinOp(
                left=UnaryOp(op=USub(), operand=in0),
                op=Add(),
                right=in1) if is_pure(in0) or is_pure(in1):
                nnode = BinOp(left=in1, op=Sub(), right=in0)
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            case _:
                return self.generic_visit(node)

    def visit_BoolOp(self, node):
        match node:
            # forall([Constant(value=c0), Constant(value=c1), Constant(value=c0 or c1)], 'c0 or c1', '_const')
            case BoolOp(
                op=Or(),
                values=[
                    Constant(value=c0),
                    Constant(value=c1)]):
                nnode = Constant(value=c0 or c1)
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall([Constant(value=c0), Constant(value=c1), Constant(value=c0 and c1)], 'c0 and c1', '_const')
            case BoolOp(
                op=And(),
                values=[
                    Constant(value=c0),
                    Constant(value=c1)]):
                nnode = Constant(value=c0 and c1)
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            case _:
                return self.generic_visit(node)

class NumpySpecialize(Rewriter):
    def visit_Call(self, node):
        match node:
            # forall(['in0', Constant(float(0.))], 'np.full(in0, c0)', 'np.zeros(in0)')
            case Call(
                func=Attribute(
                    value=Name(id=self.aliases.numpy, ctx=Load()),
                    attr='full',
                    ctx=Load()),
                args=[
                    in0,
                    Constant(float(0.))],
                keywords=[]):
                nnode = Call(
                    func=Attribute(
                        value=Name(id=self.aliases.numpy, ctx=Load()),
                        attr='zeros',
                        ctx=Load()),
                    args=[
                        in0],
                    keywords=[])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall(['in0', Constant(float(1.))], 'np.full(in0, c0)', 'np.ones(in0)')
            case Call(
                func=Attribute(
                    value=Name(id=self.aliases.numpy, ctx=Load()),
                    attr='full',
                    ctx=Load()),
                args=[
                    in0,
                    Constant(float(1.))],
                keywords=[]):
                nnode = Call(
                    func=Attribute(
                        value=Name(id=self.aliases.numpy, ctx=Load()),
                        attr='ones',
                        ctx=Load()),
                    args=[
                        in0],
                    keywords=[])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall(['in0', Constant(int(0))], 'np.full(in0, c0)', 'np.zeros(in0, dtype=int)')
            case Call(
                func=Attribute(
                    value=Name(id=self.aliases.numpy, ctx=Load()),
                    attr='full',
                    ctx=Load()),
                args=[
                    in0,
                    Constant(int(0))],
                keywords=[]):
                nnode = Call(
                    func=Attribute(
                        value=Name(id=self.aliases.numpy, ctx=Load()),
                        attr='zeros',
                        ctx=Load()),
                    args=[
                        in0],
                    keywords=[
                        keyword(
                            arg='dtype',
                            value=Name(id='int', ctx=Load()))])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall(['in0', Constant(int(1))], 'np.full(in0, c0)', 'np.ones(in0, dtype=int)')
            case Call(
                func=Attribute(
                    value=Name(id=self.aliases.numpy, ctx=Load()),
                    attr='full',
                    ctx=Load()),
                args=[
                    in0,
                    Constant(int(1))],
                keywords=[]):
                nnode = Call(
                    func=Attribute(
                        value=Name(id=self.aliases.numpy, ctx=Load()),
                        attr='ones',
                        ctx=Load()),
                    args=[
                        in0],
                    keywords=[
                        keyword(
                            arg='dtype',
                            value=Name(id='int', ctx=Load()))])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall(['in0', Constant(bool(False))], 'np.full(in0, c0)', 'np.zeros(in0, dtype=bool)')
            case Call(
                func=Attribute(
                    value=Name(id=self.aliases.numpy, ctx=Load()),
                    attr='full',
                    ctx=Load()),
                args=[
                    in0,
                    Constant(bool(False))],
                keywords=[]):
                nnode = Call(
                    func=Attribute(
                        value=Name(id=self.aliases.numpy, ctx=Load()),
                        attr='zeros',
                        ctx=Load()),
                    args=[
                        in0],
                    keywords=[
                        keyword(
                            arg='dtype',
                            value=Name(id='bool', ctx=Load()))])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall(['in0', Constant(bool(True))], 'np.full(in0, c0)', 'np.ones(in0, dtype=bool)')
            case Call(
                func=Attribute(
                    value=Name(id=self.aliases.numpy, ctx=Load()),
                    attr='full',
                    ctx=Load()),
                args=[
                    in0,
                    Constant(bool(True))],
                keywords=[]):
                nnode = Call(
                    func=Attribute(
                        value=Name(id=self.aliases.numpy, ctx=Load()),
                        attr='ones',
                        ctx=Load()),
                    args=[
                        in0],
                    keywords=[
                        keyword(
                            arg='dtype',
                            value=Name(id='bool', ctx=Load()))])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall(['in0', Constant(complex(0+0j))], 'np.full(in0, c0)', 'np.zeros(in0, dtype=complex)')
            case Call(
                func=Attribute(
                    value=Name(id=self.aliases.numpy, ctx=Load()),
                    attr='full',
                    ctx=Load()),
                args=[
                    in0,
                    Constant(complex(0+0j))],
                keywords=[]):
                nnode = Call(
                    func=Attribute(
                        value=Name(id=self.aliases.numpy, ctx=Load()),
                        attr='zeros',
                        ctx=Load()),
                    args=[
                        in0],
                    keywords=[
                        keyword(
                            arg='dtype',
                            value=Name(id='complex', ctx=Load()))])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall(['in0', Constant(complex(1+0j))], 'np.full(in0, c0)', 'np.ones(in0, dtype=complex)')
            case Call(
                func=Attribute(
                    value=Name(id=self.aliases.numpy, ctx=Load()),
                    attr='full',
                    ctx=Load()),
                args=[
                    in0,
                    Constant(complex(1+0j))],
                keywords=[]):
                nnode = Call(
                    func=Attribute(
                        value=Name(id=self.aliases.numpy, ctx=Load()),
                        attr='ones',
                        ctx=Load()),
                    args=[
                        in0],
                    keywords=[
                        keyword(
                            arg='dtype',
                            value=Name(id='complex', ctx=Load()))])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            case _:
                return self.generic_visit(node)

class NumpyReverser(Rewriter):
    def visit_Call(self, node):
        match node:
            # forall([var('v0'), 'in0', 'in1'], 'list(filter(lambda v0: in1, in0))', '[v0 for v0 in in0 if in1]')
            case Call(
                func=Name(id='list', ctx=Load()),
                args=[
                    Call(
                        func=Name(id='filter', ctx=Load()),
                        args=[
                            Lambda(
                                args=arguments(
                                    posonlyargs=[],
                                    args=[
                                        arg(arg=v0)],
                                    kwonlyargs=[],
                                    kw_defaults=[],
                                    defaults=[]),
                                body=in1),
                            in0],
                        keywords=[])],
                keywords=[]):
                nnode = ListComp(
                    elt=Name(id=v0, ctx=Load()),
                    generators=[
                        comprehension(
                            target=Name(id=v0, ctx=Store()),
                            iter=in0,
                            ifs=[
                                in1],
                            is_async=0)])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            # forall(['in0', 'in1'], 'np.extract(in0, np.array(in1))', 'np.extract(in0, in1)')
            case Call(
                func=Attribute(
                    value=Name(id=self.aliases.numpy, ctx=Load()),
                    attr='extract',
                    ctx=Load()),
                args=[
                    in0,
                    Call(
                        func=Attribute(
                            value=Name(id=self.aliases.numpy, ctx=Load()),
                            attr='array',
                            ctx=Load()),
                        args=[
                            in1],
                        keywords=[])],
                keywords=[]):
                nnode = Call(
                    func=Attribute(
                        value=Name(id=self.aliases.numpy, ctx=Load()),
                        attr='extract',
                        ctx=Load()),
                    args=[
                        in0,
                        in1],
                    keywords=[])
                self.modified = True
                copy_location(nnode, node)
                nnode.old = None
                return nnode

            case _:
                return self.generic_visit(node)

ORDER = [NumpyRewriter, NumpySpecialize, NumpyReverser]
__all__ = ('ORDER',)
__all__ += tuple([cls.__name__ for cls in ORDER])
